/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.karyawan;
import controller.manager;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.databaseConnection;

/**
 *
 * @author HP
 */
public class menuTampilan extends javax.swing.JFrame {
    
    private void show_data(){
        databaseConnection db = new databaseConnection();
        db.openConnection();
        
        ArrayList<ArrayList> members = db.all("SELECT * FROM karyawan");
        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("NIP");
        model.addColumn("Nama");
        model.addColumn("Email");
        model.addColumn("No Telpon");
        model.addColumn("Gaji");
        model.addColumn("Jam Kerja");
        model.addColumn("Status");

    for (ArrayList<String> rowData : members) {
        model.addRow(rowData.toArray());
    }
        db.closeConnection();
        tabeltampil.setModel(model);
    }

    /**
     * Creates new form menuTampilan
     */
    public menuTampilan() {
        initComponents();
        show_data();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeltampil = new javax.swing.JTable();
        tbhitung = new javax.swing.JButton();
        lbhasil = new javax.swing.JLabel();
        tbback = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabeltampil.setAutoCreateRowSorter(true);
        tabeltampil.setBackground(new java.awt.Color(255, 204, 204));
        tabeltampil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabeltampil.setShowGrid(true);
        jScrollPane1.setViewportView(tabeltampil);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 650, 220));

        tbhitung.setBackground(new java.awt.Color(116, 76, 77));
        tbhitung.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tbhitung.setForeground(new java.awt.Color(255, 255, 255));
        tbhitung.setText("Hitung");
        tbhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbhitungActionPerformed(evt);
            }
        });
        jPanel1.add(tbhitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 110, 30));

        lbhasil.setForeground(new java.awt.Color(116, 76, 77));
        lbhasil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbhasil.setText("Total Karyawan Saat Ini Adalah");
        lbhasil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(116, 76, 77), 2));
        jPanel1.add(lbhasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 190, 20));

        tbback.setBackground(new java.awt.Color(255, 204, 204));
        tbback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/login.png"))); // NOI18N
        tbback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbbackActionPerformed(evt);
            }
        });
        jPanel1.add(tbback, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/CRUD menu.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbhitungActionPerformed
        // TODO add your handling code here:
        int totalkaryawan = karyawan.hitungKaryawan();
        lbhasil.setText(Integer.toString(totalkaryawan));
       
    }//GEN-LAST:event_tbhitungActionPerformed

    private void tbbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbbackActionPerformed
        // TODO add your handling code here:
        menuUtama mnu = new menuUtama();
        mnu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tbbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuTampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuTampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuTampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuTampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuTampilan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbhasil;
    private javax.swing.JTable tabeltampil;
    private javax.swing.JButton tbback;
    private javax.swing.JButton tbhitung;
    // End of variables declaration//GEN-END:variables
}
