/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.karyawan;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.databaseConnection;

/**
 *
 * @author HP
 */
public class menuDelete extends javax.swing.JFrame {
    
    private void kosongkanform(){
        txtnip.setEditable(true);
        txtnip.setText(null);
    }
    
    private void show_data(){
        databaseConnection db = new databaseConnection();
        db.openConnection();
        
        ArrayList<ArrayList> members = db.all("SELECT * FROM karyawan");
        DefaultTableModel model = new DefaultTableModel();
       
        model.addColumn("NIP");
        model.addColumn("Nama");
        model.addColumn("Email");
        model.addColumn("No Telpon");
        model.addColumn("Gaji");
        model.addColumn("Jam Kerja");
        model.addColumn("Status");
        
    for (ArrayList<String> rowData : members) {
        model.addRow(rowData.toArray());
    }
        db.closeConnection();
        tabelhapus.setModel(model);
    }

    /**
     * Creates new form menuDelete
     */
    public menuDelete() {
        initComponents();
        show_data();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelhapus = new javax.swing.JTable();
        txtnip = new javax.swing.JTextField();
        tbnext = new javax.swing.JButton();
        tbback = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelhapus.setBackground(new java.awt.Color(255, 204, 204));
        tabelhapus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(212, 176, 181), 2));
        tabelhapus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelhapus.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabelhapus.setFocusable(false);
        tabelhapus.setShowGrid(true);
        tabelhapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelhapusMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelhapus);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 620, 120));

        txtnip.setBackground(new java.awt.Color(255, 204, 204));
        txtnip.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnipActionPerformed(evt);
            }
        });
        jPanel1.add(txtnip, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 160, 30));

        tbnext.setBackground(new java.awt.Color(255, 204, 204));
        tbnext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/logout.png"))); // NOI18N
        tbnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnextActionPerformed(evt);
            }
        });
        jPanel1.add(tbnext, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, -1, -1));

        tbback.setBackground(new java.awt.Color(255, 204, 204));
        tbback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/login.png"))); // NOI18N
        tbback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbbackActionPerformed(evt);
            }
        });
        jPanel1.add(tbback, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(116, 76, 77));
        jLabel2.setText("NIP Yang Dipilih :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 110, 30));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/CRUD menu.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelhapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelhapusMouseClicked
        // TODO add your handling code here:
        int baris = tabelhapus.rowAtPoint(evt.getPoint());
        String nip_karyawan = tabelhapus.getValueAt(baris, 0). toString();
        txtnip.setText(nip_karyawan);
    }//GEN-LAST:event_tabelhapusMouseClicked

    private void txtnipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnipActionPerformed

    private void tbnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnextActionPerformed
        // TODO add your handling code here:
        try{
            karyawan karyawan = new karyawan();
            
            int intValue = Integer.parseInt(txtnip.getText());
            karyawan.find(intValue);

             if (karyawan.delete()) {
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus!");
                show_data();
                kosongkanform();

            }else{
                JOptionPane.showMessageDialog(null, "Data Gagal Dihapus!");
            }
        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Periksa NIP Anda Kembali!");
            return;
        }
    }//GEN-LAST:event_tbnextActionPerformed

    private void tbbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbbackActionPerformed
        // TODO add your handling code here:
        menuUtama mnu = new menuUtama();
        mnu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tbbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuDelete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelhapus;
    private javax.swing.JButton tbback;
    private javax.swing.JButton tbnext;
    private javax.swing.JTextField txtnip;
    // End of variables declaration//GEN-END:variables
}
