/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.karyawan;
import controller.manager;
import controller.staff;
import controller.staff_magang;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.databaseConnection;

/**
 *
 * @author HP
 */
public class menuUpdate extends javax.swing.JFrame {
    private void show_data(){
        databaseConnection db = new databaseConnection();    
        db.openConnection();
        
        ArrayList<ArrayList> members = db.all("SELECT * FROM karyawan");
        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("NIP");
        model.addColumn("Nama Karyawan");
        model.addColumn("Email Karyawan");
        model.addColumn("No Telpon");
        model.addColumn("Gaji");
        model.addColumn("Jam Kerja");
        model.addColumn("Status");

    for (ArrayList<String> rowData : members) {
        model.addRow(rowData.toArray());
    }
        db.closeConnection();
        tabelupdate.setModel(model);
    }
    
    private void kosongkanform(){
        txtnip.setEditable(true);
        txtnip.setText(null);
        txtnama.setText(null);
        txtemail.setText(null);
        txttelp.setText(null);
    }

    /**
     * Creates new form menuUpdate
     */
    public menuUpdate() {
        initComponents();
        show_data();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelupdate = new javax.swing.JTable();
        txtnip = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txttelp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tbnext = new javax.swing.JButton();
        tbback = new javax.swing.JButton();
        cbjabatan = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelupdate.setBackground(new java.awt.Color(255, 204, 204));
        tabelupdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(212, 176, 181), 2));
        tabelupdate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelupdate.setShowGrid(true);
        tabelupdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelupdateMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelupdate);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 640, 110));

        txtnip.setBackground(new java.awt.Color(255, 204, 204));
        txtnip.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(211, 176, 181), 2));
        jPanel1.add(txtnip, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 240, 30));

        txtnama.setBackground(new java.awt.Color(255, 204, 204));
        txtnama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(211, 176, 181), 2));
        jPanel1.add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 240, 30));

        txtemail.setBackground(new java.awt.Color(255, 204, 204));
        txtemail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(211, 176, 181), 2));
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 240, 30));

        txttelp.setBackground(new java.awt.Color(255, 204, 204));
        txttelp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(211, 176, 181), 2));
        txttelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelpActionPerformed(evt);
            }
        });
        jPanel1.add(txttelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 240, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("NIP");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Nama Karyawan");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Email Karyawan");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("No Telpon");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, -1));

        tbnext.setBackground(new java.awt.Color(255, 204, 204));
        tbnext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/logout.png"))); // NOI18N
        tbnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnextActionPerformed(evt);
            }
        });
        jPanel1.add(tbnext, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, -1, -1));

        tbback.setBackground(new java.awt.Color(255, 204, 204));
        tbback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/login.png"))); // NOI18N
        tbback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbbackActionPerformed(evt);
            }
        });
        jPanel1.add(tbback, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, -1, -1));

        cbjabatan.setBackground(new java.awt.Color(255, 204, 204));
        cbjabatan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbjabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "staff", "manager", "staff magang" }));
        cbjabatan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(212, 176, 181)));
        jPanel1.add(cbjabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 240, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Jabatan");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/CRUD menu.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelupdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelupdateMouseClicked
        // TODO add your handling code here:
        int baris = tabelupdate.rowAtPoint(evt.getPoint());
        String nip_karyawan = tabelupdate.getValueAt(baris, 0). toString();
        txtnip.setText(nip_karyawan);
        
        String nama = tabelupdate.getValueAt(baris, 1). toString();
        txtnama.setText(nama);
        
        String email = tabelupdate.getValueAt(baris, 2). toString();
        txtemail.setText(email);
        
        String telp = tabelupdate.getValueAt(baris, 3). toString();
        txttelp.setText(telp);
        
    }//GEN-LAST:event_tabelupdateMouseClicked

    private void tbnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnextActionPerformed
        // TODO add your handling code here:
        try{
            int intValue = Integer.parseInt(txtnip.getText());
            
            karyawan k = new karyawan();
            k.setStatus("Aktif");
            String statusnya = k.getStatus();

            String pilih = (String) cbjabatan.getSelectedItem();
                if (pilih == "manager") {
                    manager m = new manager(intValue, txtnama.getText(),txtemail.getText(),txttelp.getText(), 2, 500000.0, 3000000.0,statusnya);
                    double gajimanager = m.hitungGaji();   

                    m.setjamKerja(10, true);
                    int durasi = m.getjamKerja();

                    m.nip_karyawan = intValue;
                    m.nama_karyawan = txtnama.getText();
                    m.email_karyawan = txtemail.getText();
                    m.nomor_telpon = txttelp.getText();
                    m.gaji = gajimanager;
                    m.status = statusnya;
                    m.durasi_kerja = durasi;

                    if (m.update()) {
                        JOptionPane.showMessageDialog(null, "Data Berhasil Diperbarui!");
                        show_data();
                        kosongkanform();
                    } else {
                        JOptionPane.showMessageDialog(null, "Data Gagal Diperbarui!");
                    }

                }else if (pilih == "staff") {
                    staff s = new staff(intValue, txtnama.getText(),txtemail.getText(),txttelp.getText(), 3000000, statusnya);
                    double gajistaff = s.hitungGaji();

                    s.setjamKerja(8);
                    int durasi = s.getjamKerja();

                    s.nip_karyawan = intValue;
                    s.nama_karyawan = txtnama.getText();
                    s.email_karyawan = txtemail.getText();
                    s.nomor_telpon = txttelp.getText();
                    s.gaji = gajistaff;
                    s.status = statusnya;
                    s.durasi_kerja = durasi;

                    if (s.update()) {
                        JOptionPane.showMessageDialog(null, "Data Berhasil Diperbarui!");
                        show_data();
                        kosongkanform();
                    } else {
                        JOptionPane.showMessageDialog(null, "Data Gagal Diperbarui!");
                    }

                }else if (pilih == "staff magang") {
                    staff_magang sm = new staff_magang(intValue, txtnama.getText(),txtemail.getText(),txttelp.getText(),2, 3000000, statusnya);
                    double gajimagang = sm.hitungGaji();

                    sm.setjamKerja(3, true, 2);
                    int durasi = sm.getjamKerja();

                    sm.nip_karyawan = intValue;
                    sm.nama_karyawan = txtnama.getText();
                    sm.email_karyawan = txtemail.getText();
                    sm.nomor_telpon = txttelp.getText();
                    sm.gaji = gajimagang;
                    sm.status = statusnya;
                    sm.durasi_kerja = durasi;

                    if (sm.update()) {
                        JOptionPane.showMessageDialog(null, "Data Berhasil Diperbarui!");
                        show_data();
                        kosongkanform();
                    } else {
                        JOptionPane.showMessageDialog(null, "Data Gagal Diperbarui!");
                    }
                }
        }catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Periksa NIP Anda Kembali!");
        return;
        }
    }//GEN-LAST:event_tbnextActionPerformed

    private void tbbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbbackActionPerformed
        // TODO add your handling code here:
        menuUtama mnu = new menuUtama();
        mnu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tbbackActionPerformed

    private void txttelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbjabatan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelupdate;
    private javax.swing.JButton tbback;
    private javax.swing.JButton tbnext;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnip;
    private javax.swing.JTextField txttelp;
    // End of variables declaration//GEN-END:variables
}
